/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "design_synth.sv:6" *)
module MEM_256bytes(addr, write_en, read_en, write_in, read_out);
  (* src = "design_synth.sv:20" *)
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  (* src = "design_synth.sv:8" *)
  input [1:0] addr;
  (* src = "design_synth.sv:6" *)
  wire [7:0] \mem_array[0] ;
  (* src = "design_synth.sv:6" *)
  wire [7:0] \mem_array[1] ;
  (* src = "design_synth.sv:6" *)
  wire [7:0] \mem_array[2] ;
  (* src = "design_synth.sv:6" *)
  wire [7:0] \mem_array[3] ;
  (* src = "design_synth.sv:12" *)
  input read_en;
  (* src = "design_synth.sv:14" *)
  output [7:0] read_out;
  (* src = "design_synth.sv:11" *)
  input write_en;
  (* src = "design_synth.sv:13" *)
  input [7:0] write_in;
  assign _02_ = ~ write_en;
  assign _03_ = ~ _32_;
  assign _05_ = ~ _31_;
  assign _07_ = ~ _30_;
  assign _09_ = ~ _29_;
  assign _11_ = ~ read_en;
  assign _12_ = | { _27_, _28_ };
  assign _14_ = | { _22_, _23_ };
  assign _16_ = | { _22_, _24_ };
  assign _18_ = | { _22_, _25_ };
  assign _20_ = | { _22_, _26_ };
  assign _22_ = _02_ & 1'b1;
  assign _13_ = _03_ & 1'b1;
  assign _23_ = write_en & _13_;
  assign _15_ = _05_ & 1'b1;
  assign _24_ = write_en & _15_;
  assign _17_ = _07_ & 1'b1;
  assign _25_ = write_en & _17_;
  assign _19_ = _09_ & 1'b1;
  assign _26_ = write_en & _19_;
  assign _21_ = _11_ & 1'b1;
  assign _27_ = _02_ & _21_;
  assign _28_ = write_en & 1'b1;
  assign _01_ = ~ _12_;
  \$dlatch  #(
    .EN_POLARITY(32'd1),
    .WIDTH(32'd8)
  ) _57_ (
    .D(_00_),
    .EN(_01_),
    .Q(read_out)
  );
  assign _04_ = ~ _14_;
  \$dlatch  #(
    .EN_POLARITY(32'd1),
    .WIDTH(32'd8)
  ) _59_ (
    .D(write_in),
    .EN(_04_),
    .Q(\mem_array[0] )
  );
  assign _06_ = ~ _16_;
  \$dlatch  #(
    .EN_POLARITY(32'd1),
    .WIDTH(32'd8)
  ) _61_ (
    .D(write_in),
    .EN(_06_),
    .Q(\mem_array[1] )
  );
  assign _08_ = ~ _18_;
  \$dlatch  #(
    .EN_POLARITY(32'd1),
    .WIDTH(32'd8)
  ) _63_ (
    .D(write_in),
    .EN(_08_),
    .Q(\mem_array[2] )
  );
  assign _10_ = ~ _20_;
  \$dlatch  #(
    .EN_POLARITY(32'd1),
    .WIDTH(32'd8)
  ) _65_ (
    .D(write_in),
    .EN(_10_),
    .Q(\mem_array[3] )
  );
  function [7:0] _66_;
    input [7:0] a;
    input [23:0] b;
    input [2:0] s;
    (* src = "design_synth.sv:6" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _66_ = b[7:0];
      3'b?1?:
        _66_ = b[15:8];
      3'b1??:
        _66_ = b[23:16];
      default:
        _66_ = a;
    endcase
  endfunction
  assign _00_ = _66_(\mem_array[0] , { \mem_array[1] , \mem_array[2] , \mem_array[3]  }, { _31_, _30_, _29_ });
  assign _29_ = addr == (* src = "design_synth.sv:6" *) 2'b11;
  assign _30_ = addr == (* src = "design_synth.sv:6" *) 2'b10;
  assign _31_ = addr == (* src = "design_synth.sv:6" *) 2'b01;
  assign _32_ = ! (* src = "design_synth.sv:6" *) addr;
endmodule
